language: objective-c
notifications:
  email:
    on_success: never
    on_failure: change
before_script:
- ./script/add-key
- export JANKY_BRANCH=$TRAVIS_BRANCH
- export JANKY_SHA1=$TRAVIS_COMMIT
script:
- ./script/build
# - ./script/run-ci-specs
after_script: ./script/remove-key
cache:
  directories:
    - build/node_modules
